
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: dungeon_crawler_development

production:
  <<: *default
  database: rails_crawler_database
  username: rails_crawler_user
  password: <%= ENV["DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>