
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: dungeon_crawler_development

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # <<: *default
  # database: rails_crawler_new_database
  # username: rails_crawler_new_user
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>